version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - npm install
  pre_build:
    commands:
      - echo "Build started on `date`"
  build:
    commands:
      - echo Running build process...
      - npm run build
  post_build:
    commands:
      - echo "Build Completed on `date`"

artifacts:
  files:
    - '**/*'
