version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - npm install
  pre_build:
    commands:
      - echo Installing latest TypeScript...
      - npm install typescript@latest --save-dev
      - echo "Build started on `date`"
  build:
    commands:
      - echo Building frontend...
      - npm run build:frontend
      - echo Building server...
      - npm run build:server
  post_build:
    commands:
      - echo "Build Completed on `date`"

artifacts:
  files:
    - 'build/**/*'
    - 'frontend/dist/**/*'
  base-directory: .
