version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - sleep 2  # 2초 대기 (테스트용)

  pre_build:
    commands:
      - echo "Pre-build phase..."
      - date  # 현재 날짜 및 시간 출력
      - sleep 2

  build:
    commands:
      - echo "Build phase started..."
      - echo "Running some fake build commands..."
      - sleep 3
      - echo "Build phase completed."

  post_build:
    commands:
      - echo "Post-build phase..."
      - echo "Build completed successfully!"
      - sleep 2

artifacts:
  files:
    - "**/*"
